Revert "feat(owl-bot): Acknowledge Ignore label Before Updating PRs (#2983)" (#3003)
This reverts commit dc1edad393d29be133fc56541ea336e647899156.

Saw error:
TypeError
fs.rmSync is not a function
TypeError: fs.rmSync is not a function at fetchConfigs (/workspace/build/src/fetch-configs.js:63:12) at refreshConfigs (/workspace/build/src/handlers.js:213:80) at runMicrotasks () at async /workspace/build/src/owl-bot.js:155:9 at async Promise.all (index 0) at async /workspace/node_modules/gcf-utils/build/src/gcf-utils.js:370:21
Service
owl_bot