fix: pin typescript to 4.8.4 for four more bots
Upgrading to typescript 4.9 results in the same error for all these bots:

```
node_modules/@types/node/globals.d.ts:72:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; timeout(milliseconds: number): AbortSignal; }', but here has type '{ new (): AbortSignal; prototype: AbortSignal; }'.

72 declare var AbortSignal: {
               ~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:2071:13
    2071 declare var AbortSignal: {
                     ~~~~~~~~~~~
    'AbortSignal' was also declared here.
```

After merging, I'll close the following PRs:
https://github.com/googleapis/repo-automation-bots/pull/4803
https://github.com/googleapis/repo-automation-bots/pull/4796
https://github.com/googleapis/repo-automation-bots/pull/4795
https://github.com/googleapis/repo-automation-bots/pull/4787