fix: failed to fetch docker images' timestamps (#5061)
Owl Bot was logging errors like this:
```
fetching https://gcr.io/v2/cloud-devrel-public-resources/owlbot-go/manifests/sha256:bd3adb7c0c9cfb8ead23d2abf351ee5935163096e5fb4af1bedf22b93023d058
Error: HTTP error, status code: 404
    at IncomingMessage.<anonymous> (/usr/src/app/build/src/docker-api.js:58:28)
    at IncomingMessage.emit (events.js:412:35)
    at IncomingMessage.emit (domain.js:475:12)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```
which were not fatal. But they were a distraction when I was trying to
debug an issue. Plus, the .OwlBot.lock.yaml file didn't get a timestamp
which makes generated PRs easier to review.