chore: typescript 4.9.4 for blunderbuss (#4922)
Probot's context.d.ts broke typescript:
```
src/utils.ts:120:10 - error TS2590: Expression produces a union type that is too complex to represent.

120       ...context.repo(),
```

Instead of https://togithub.com/googleapis/repo-automation-bots/pull/4877