fix: update gcb nodejs runtime to nodejs20, since GCB no longer supports nodejs18 (#5966)
This is to unblock build errors:

```
ERROR: (gcloud.functions.deploy) argument `--runtime`: nodejs18 is not a supported runtime on GCF 1st gen. Use `gcloud functions runtimes list` to get a list of available runtimes
```