fix(owl-bot): add back tmp to dependencies (#5970)
Builds have been failing since [this
commit](https://github.com/googleapis/repo-automation-bots/commit/97ca3dd013fbb6953396aac90472861c99aebd33)
due to:

```
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Function failed on loading user code. This is likely due to a bug in the user code. Error message: Provided module can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'tmp'
```

It looks like the npm audit --fix removed this dependency, adding back
in.